on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4.0.0
      with:
        node-version: ${{ secrets.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build 

    - name: scp
      uses: appleboy/scp-action@v0.0.1
      with:
        host: 8.140.249.87
        port: 22
        username: root
        password: ${{ secrets.PASSWORD }}
        source: test/
        target: /home


